### ISSUE TITLE
No such file or directory >> Problema con la SO de Epson

### ISSUE THREAD

**Issue by MatiasEzequielDiaz** [paxapos/fiscalberry#124]
Hola. Estoy necesitando ayuda. Quiero hacer funcionar la impresora en un Raspberry Pi y la SO me arroja un error. Lo probe tanto con FiscalBerry como con el example que trae la misma descarga de Epson. En un Ubuntu convencional esto funciona perfecto, pero no entiendo bien por que en la Raspberry no. Que soluciones puedo darle? Se debe al tipo de arquitectura del procesador?

El error que me muestra es el siguiente:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/fiscalberry/Traductores/TraductoresHandler.py", line 63, in runTraductor
    traductor = init_printer_traductor(printerName)
  File "/home/pi/fiscalberry/Traductores/TraductoresHandler.py", line 57, in init_printer_traductor
    comando = comandoClass(**dictSectionConf)
  File "/home/pi/fiscalberry/ComandoInterface.py", line 145, in __init__
    self.conector = ConectorDriverComando(self, driver, **kwargs)
  File "/home/pi/fiscalberry/ConectorDriverComando.py", line 24, in __init__
    driverModule = importlib.import_module(libraryName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/fiscalberry/Drivers/Epson2GenDriver.py", line 21, in <module>
    EpsonLibInterface = ctypes.cdll.LoadLibrary(fullpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/libEpsonFiscalInterface.so: cannot open shared object file: No such file or directory

```

Desde ya muchisimas gracias y un saludo.

**Comment by alevilar** [comment]
hola!, como estas? consulta, estas queriendo imprimir en una Epson de 2da
generacion?

tenes el archivo /lib/libEpsonFiscalInterface.so ? y tenes permisos para
abrirlo?

espero poder ayudarte. slds!

**Comment by alevilar** [comment]
Cerrada en triage masivo de backlog (más de 1 año sin resolución). Si sigue vigente, reabrir con contexto actualizado. 🤖
