### ISSUE TITLE
la primera vez que se ejecuta no inicia

### ISSUE THREAD

**Issue by alevilar** [paxapos/fiscalberry#127]
pi@aaaa:~ $ sudo ./fiscalberry-pi 
NUEVO User config files creado en /root/.config/Fiscalberry/config.ini
Traceback (most recent call last):
  File "cli.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "common/fiscalberry_logger.py", line 6, in <module>
  File "common/Configberry.py", line 31, in __init__
  File "common/Configberry.py", line 177, in __create_config_if_not_exists
NameError: name 'defaultConfig' is not defined
[PYI-885:ERROR] Failed to execute script 'cli' due to unhandled exception!

**Comment by alevilar** [comment]
Cerrada en triage masivo de backlog (más de 1 año sin resolución). Si sigue vigente, reabrir con contexto actualizado. 🤖
