### ISSUE TITLE
error al iniciar server.py

### ISSUE THREAD

**Issue by juanmarinelli** [paxapos/fiscalberry#99]
Hola! estuve configurando toda la libreria bajo windows, con python 2.7.17, pero a la hora de ejecutar server.py me tira el siguiente error:
python server.py
Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from FiscalberryApp import FiscalberryApp
  File "C:\xampp\htdocs\fiscalberry\FiscalberryApp.py", line 39, in <module>
    logging.config.fileConfig(root+'/logging.ini')
  File "C:\Python27\lib\logging\config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "C:\Python27\lib\logging\config.py", line 163, in _install_handlers
    h = klass(*args)
  File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: 'C:\\tmp\\fiscal_printer_driver.lo
g'

Queria saber si alguno sabe que seria porque he probado varias cosas pero sin resultados positivos
Gracias !

**Comment by juanmarinelli** [comment]
Solucionado, cambie args=('/tmp/fiscal_printer_driver.log',) -> args=('fiscal_printer_driver.log', 'a') de [handler_fileHandlerFiscalPrinterDriver]

**Comment by joseluisbossio** [comment]
5$
